title: TDAxis
description: Generación y Control de Contenido Audiovisual Utilizando TouchDesigner, Ableton Live y los movimientos del cuerpo a través del Perception Neuron
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
